name: Pelagios Network
markdown: kramdown
#theme: jekyll-theme-cayman
permalink: pretty

collections_dir: content
collections:
  activities:
    output: true
  case-studies:
    output: true
  partners:
    output: false

sass:
  style: compact # possible values: nested expanded compact compressed
url: "https://pelagios.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: UA—XXXXXXXX-X
